//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenciaActualizada
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/", ConfigurationName="ReferenciaActualizada.Service")]
    public interface Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/registerRequest", ReplyAction="http://soap/Service/registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.registerResponse> registerAsync(ReferenciaActualizada.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/verifySessionRequest", ReplyAction="http://soap/Service/verifySessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.verifySessionResponse> verifySessionAsync(ReferenciaActualizada.verifySessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/loginRequest", ReplyAction="http://soap/Service/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.loginResponse> loginAsync(ReferenciaActualizada.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/deleteFileRequest", ReplyAction="http://soap/Service/deleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.deleteFileResponse> deleteFileAsync(ReferenciaActualizada.deleteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/uploadFileRequest", ReplyAction="http://soap/Service/uploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.uploadFileResponse> uploadFileAsync(ReferenciaActualizada.uploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/createFolderRequest", ReplyAction="http://soap/Service/createFolderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.createFolderResponse> createFolderAsync(ReferenciaActualizada.createFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/downloadFileRequest", ReplyAction="http://soap/Service/downloadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.downloadFileResponse> downloadFileAsync(ReferenciaActualizada.downloadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/getUserFilesRequest", ReplyAction="http://soap/Service/getUserFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.getUserFilesResponse> getUserFilesAsync(ReferenciaActualizada.getUserFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/moveFileRequest", ReplyAction="http://soap/Service/moveFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.moveFileResponse> moveFileAsync(ReferenciaActualizada.moveFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/getSharedFilesRequest", ReplyAction="http://soap/Service/getSharedFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.getSharedFilesResponse> getSharedFilesAsync(ReferenciaActualizada.getSharedFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/seeStorageTreeRequest", ReplyAction="http://soap/Service/seeStorageTreeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.seeStorageTreeResponse> seeStorageTreeAsync(ReferenciaActualizada.seeStorageTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/stopSharingFileRequest", ReplyAction="http://soap/Service/stopSharingFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.stopSharingFileResponse> stopSharingFileAsync(ReferenciaActualizada.stopSharingFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/getSubFolderFilesRequest", ReplyAction="http://soap/Service/getSubFolderFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.getSubFolderFilesResponse> getSubFolderFilesAsync(ReferenciaActualizada.getSubFolderFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/shareFileRequest", ReplyAction="http://soap/Service/shareFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.shareFileResponse> shareFileAsync(ReferenciaActualizada.shareFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/deleteFolderRequest", ReplyAction="http://soap/Service/deleteFolderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferenciaActualizada.deleteFolderResponse> deleteFolderAsync(ReferenciaActualizada.deleteFolderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class user
    {
        
        private string nameField;
        
        private string surnameField;
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class folder
    {
        
        private int idField;
        
        private string nameField;
        
        private string pathField;
        
        private int userIdField;
        
        private double sizeField;
        
        private int nodeIdField;
        
        private int fatherIdField;
        
        private int backNodeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int nodeId
        {
            get
            {
                return this.nodeIdField;
            }
            set
            {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int fatherId
        {
            get
            {
                return this.fatherIdField;
            }
            set
            {
                this.fatherIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int backNodeId
        {
            get
            {
                return this.backNodeIdField;
            }
            set
            {
                this.backNodeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class file
    {
        
        private int idField;
        
        private string nameField;
        
        private string pathField;
        
        private byte[] fileDataField;
        
        private double sizeField;
        
        private int userIdField;
        
        private int folderIdField;
        
        private int nodeIdField;
        
        private int backNodeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] fileData
        {
            get
            {
                return this.fileDataField;
            }
            set
            {
                this.fileDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int folderId
        {
            get
            {
                return this.folderIdField;
            }
            set
            {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int nodeId
        {
            get
            {
                return this.nodeIdField;
            }
            set
            {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int backNodeId
        {
            get
            {
                return this.backNodeIdField;
            }
            set
            {
                this.backNodeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class response
    {
        
        private int statusCodeField;
        
        private string detailsField;
        
        private string jsonField;
        
        private byte[] fileDataField;
        
        private int mainNodeField;
        
        private int backUpNodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string json
        {
            get
            {
                return this.jsonField;
            }
            set
            {
                this.jsonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] fileData
        {
            get
            {
                return this.fileDataField;
            }
            set
            {
                this.fileDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int mainNode
        {
            get
            {
                return this.mainNodeField;
            }
            set
            {
                this.mainNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int backUpNode
        {
            get
            {
                return this.backUpNodeField;
            }
            set
            {
                this.backUpNodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class registerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.user arg0;
        
        public registerRequest()
        {
        }
        
        public registerRequest(ReferenciaActualizada.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class registerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public registerResponse()
        {
        }
        
        public registerResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifySession", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class verifySessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public verifySessionRequest()
        {
        }
        
        public verifySessionRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifySessionResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class verifySessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public verifySessionResponse()
        {
        }
        
        public verifySessionResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.user arg0;
        
        public loginRequest()
        {
        }
        
        public loginRequest(ReferenciaActualizada.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public loginResponse()
        {
        }
        
        public loginResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public deleteFileRequest()
        {
        }
        
        public deleteFileRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public deleteFileResponse()
        {
        }
        
        public deleteFileResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class uploadFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.file arg0;
        
        public uploadFileRequest()
        {
        }
        
        public uploadFileRequest(ReferenciaActualizada.file arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class uploadFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public uploadFileResponse()
        {
        }
        
        public uploadFileResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolder", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class createFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.folder arg0;
        
        public createFolderRequest()
        {
        }
        
        public createFolderRequest(ReferenciaActualizada.folder arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolderResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class createFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public createFolderResponse()
        {
        }
        
        public createFolderResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class downloadFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public downloadFileRequest()
        {
        }
        
        public downloadFileRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class downloadFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public downloadFileResponse()
        {
        }
        
        public downloadFileResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserFiles", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getUserFilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getUserFilesRequest()
        {
        }
        
        public getUserFilesRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserFilesResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getUserFilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public getUserFilesResponse()
        {
        }
        
        public getUserFilesResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class moveFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public moveFileRequest()
        {
        }
        
        public moveFileRequest(int arg0, int arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class moveFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public moveFileResponse()
        {
        }
        
        public moveFileResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSharedFiles", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getSharedFilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getSharedFilesRequest()
        {
        }
        
        public getSharedFilesRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSharedFilesResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getSharedFilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public getSharedFilesResponse()
        {
        }
        
        public getSharedFilesResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTree", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class seeStorageTreeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public seeStorageTreeRequest()
        {
        }
        
        public seeStorageTreeRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTreeResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class seeStorageTreeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public seeStorageTreeResponse()
        {
        }
        
        public seeStorageTreeResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class stopSharingFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public stopSharingFileRequest()
        {
        }
        
        public stopSharingFileRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class stopSharingFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public stopSharingFileResponse()
        {
        }
        
        public stopSharingFileResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubFolderFiles", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getSubFolderFilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getSubFolderFilesRequest()
        {
        }
        
        public getSubFolderFilesRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubFolderFilesResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getSubFolderFilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public getSubFolderFilesResponse()
        {
        }
        
        public getSubFolderFilesResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class shareFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public shareFileRequest()
        {
        }
        
        public shareFileRequest(string arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class shareFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public shareFileResponse()
        {
        }
        
        public shareFileResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolder", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public deleteFolderRequest()
        {
        }
        
        public deleteFolderRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolderResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenciaActualizada.response @return;
        
        public deleteFolderResponse()
        {
        }
        
        public deleteFolderResponse(ReferenciaActualizada.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceChannel : ReferenciaActualizada.Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ReferenciaActualizada.Service>, ReferenciaActualizada.Service
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.registerResponse> ReferenciaActualizada.Service.registerAsync(ReferenciaActualizada.registerRequest request)
        {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.registerResponse> registerAsync(ReferenciaActualizada.user arg0)
        {
            ReferenciaActualizada.registerRequest inValue = new ReferenciaActualizada.registerRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.verifySessionResponse> ReferenciaActualizada.Service.verifySessionAsync(ReferenciaActualizada.verifySessionRequest request)
        {
            return base.Channel.verifySessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.verifySessionResponse> verifySessionAsync(string arg0)
        {
            ReferenciaActualizada.verifySessionRequest inValue = new ReferenciaActualizada.verifySessionRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).verifySessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.loginResponse> ReferenciaActualizada.Service.loginAsync(ReferenciaActualizada.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.loginResponse> loginAsync(ReferenciaActualizada.user arg0)
        {
            ReferenciaActualizada.loginRequest inValue = new ReferenciaActualizada.loginRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.deleteFileResponse> ReferenciaActualizada.Service.deleteFileAsync(ReferenciaActualizada.deleteFileRequest request)
        {
            return base.Channel.deleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.deleteFileResponse> deleteFileAsync(int arg0)
        {
            ReferenciaActualizada.deleteFileRequest inValue = new ReferenciaActualizada.deleteFileRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).deleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.uploadFileResponse> ReferenciaActualizada.Service.uploadFileAsync(ReferenciaActualizada.uploadFileRequest request)
        {
            return base.Channel.uploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.uploadFileResponse> uploadFileAsync(ReferenciaActualizada.file arg0)
        {
            ReferenciaActualizada.uploadFileRequest inValue = new ReferenciaActualizada.uploadFileRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).uploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.createFolderResponse> ReferenciaActualizada.Service.createFolderAsync(ReferenciaActualizada.createFolderRequest request)
        {
            return base.Channel.createFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.createFolderResponse> createFolderAsync(ReferenciaActualizada.folder arg0)
        {
            ReferenciaActualizada.createFolderRequest inValue = new ReferenciaActualizada.createFolderRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).createFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.downloadFileResponse> ReferenciaActualizada.Service.downloadFileAsync(ReferenciaActualizada.downloadFileRequest request)
        {
            return base.Channel.downloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.downloadFileResponse> downloadFileAsync(int arg0)
        {
            ReferenciaActualizada.downloadFileRequest inValue = new ReferenciaActualizada.downloadFileRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).downloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.getUserFilesResponse> ReferenciaActualizada.Service.getUserFilesAsync(ReferenciaActualizada.getUserFilesRequest request)
        {
            return base.Channel.getUserFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.getUserFilesResponse> getUserFilesAsync(int arg0)
        {
            ReferenciaActualizada.getUserFilesRequest inValue = new ReferenciaActualizada.getUserFilesRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).getUserFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.moveFileResponse> ReferenciaActualizada.Service.moveFileAsync(ReferenciaActualizada.moveFileRequest request)
        {
            return base.Channel.moveFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.moveFileResponse> moveFileAsync(int arg0, int arg1, string arg2)
        {
            ReferenciaActualizada.moveFileRequest inValue = new ReferenciaActualizada.moveFileRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((ReferenciaActualizada.Service)(this)).moveFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.getSharedFilesResponse> ReferenciaActualizada.Service.getSharedFilesAsync(ReferenciaActualizada.getSharedFilesRequest request)
        {
            return base.Channel.getSharedFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.getSharedFilesResponse> getSharedFilesAsync(int arg0)
        {
            ReferenciaActualizada.getSharedFilesRequest inValue = new ReferenciaActualizada.getSharedFilesRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).getSharedFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.seeStorageTreeResponse> ReferenciaActualizada.Service.seeStorageTreeAsync(ReferenciaActualizada.seeStorageTreeRequest request)
        {
            return base.Channel.seeStorageTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.seeStorageTreeResponse> seeStorageTreeAsync(int arg0)
        {
            ReferenciaActualizada.seeStorageTreeRequest inValue = new ReferenciaActualizada.seeStorageTreeRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).seeStorageTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.stopSharingFileResponse> ReferenciaActualizada.Service.stopSharingFileAsync(ReferenciaActualizada.stopSharingFileRequest request)
        {
            return base.Channel.stopSharingFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.stopSharingFileResponse> stopSharingFileAsync(int arg0)
        {
            ReferenciaActualizada.stopSharingFileRequest inValue = new ReferenciaActualizada.stopSharingFileRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).stopSharingFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.getSubFolderFilesResponse> ReferenciaActualizada.Service.getSubFolderFilesAsync(ReferenciaActualizada.getSubFolderFilesRequest request)
        {
            return base.Channel.getSubFolderFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.getSubFolderFilesResponse> getSubFolderFilesAsync(int arg0)
        {
            ReferenciaActualizada.getSubFolderFilesRequest inValue = new ReferenciaActualizada.getSubFolderFilesRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).getSubFolderFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.shareFileResponse> ReferenciaActualizada.Service.shareFileAsync(ReferenciaActualizada.shareFileRequest request)
        {
            return base.Channel.shareFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.shareFileResponse> shareFileAsync(string arg0, int arg1)
        {
            ReferenciaActualizada.shareFileRequest inValue = new ReferenciaActualizada.shareFileRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ReferenciaActualizada.Service)(this)).shareFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenciaActualizada.deleteFolderResponse> ReferenciaActualizada.Service.deleteFolderAsync(ReferenciaActualizada.deleteFolderRequest request)
        {
            return base.Channel.deleteFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaActualizada.deleteFolderResponse> deleteFolderAsync(int arg0)
        {
            ReferenciaActualizada.deleteFolderRequest inValue = new ReferenciaActualizada.deleteFolderRequest();
            inValue.arg0 = arg0;
            return ((ReferenciaActualizada.Service)(this)).deleteFolderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:2376/app");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.ServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.ServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicePort,
        }
    }
}
