//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiReferencia
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/", ConfigurationName="MiReferencia.Service")]
    public interface Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/registerRequest", ReplyAction="http://soap/Service/registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.registerResponse> registerAsync(MiReferencia.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/loginRequest", ReplyAction="http://soap/Service/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.loginResponse> loginAsync(MiReferencia.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/createFolderRequest", ReplyAction="http://soap/Service/createFolderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.createFolderResponse> createFolderAsync(MiReferencia.createFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/uploadFileRequest", ReplyAction="http://soap/Service/uploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.uploadFileResponse> uploadFileAsync(MiReferencia.uploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/downloadFileRequest", ReplyAction="http://soap/Service/downloadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.downloadFileResponse> downloadFileAsync(MiReferencia.downloadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/deleteFileRequest", ReplyAction="http://soap/Service/deleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.deleteFileResponse> deleteFileAsync(MiReferencia.deleteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/getUserFilesRequest", ReplyAction="http://soap/Service/getUserFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.getUserFilesResponse> getUserFilesAsync(MiReferencia.getUserFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/deleteFolderRequest", ReplyAction="http://soap/Service/deleteFolderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.deleteFolderResponse> deleteFolderAsync(MiReferencia.deleteFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/shareFileRequest", ReplyAction="http://soap/Service/shareFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.shareFileResponse> shareFileAsync(MiReferencia.shareFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/stopSharingFileRequest", ReplyAction="http://soap/Service/stopSharingFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.stopSharingFileResponse> stopSharingFileAsync(MiReferencia.stopSharingFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/moveFileRequest", ReplyAction="http://soap/Service/moveFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.moveFileResponse> moveFileAsync(MiReferencia.moveFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/seeStorageTreeRequest", ReplyAction="http://soap/Service/seeStorageTreeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.seeStorageTreeResponse> seeStorageTreeAsync(MiReferencia.seeStorageTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/Service/verifySessionRequest", ReplyAction="http://soap/Service/verifySessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MiReferencia.verifySessionResponse> verifySessionAsync(MiReferencia.verifySessionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class user
    {
        
        private string nameField;
        
        private string surnameField;
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class file
    {
        
        private int idField;
        
        private string nameField;
        
        private string pathField;
        
        private byte[] fileDataField;
        
        private double sizeField;
        
        private int userIdField;
        
        private int folderIdField;
        
        private int nodeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] fileData
        {
            get
            {
                return this.fileDataField;
            }
            set
            {
                this.fileDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int folderId
        {
            get
            {
                return this.folderIdField;
            }
            set
            {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int nodeId
        {
            get
            {
                return this.nodeIdField;
            }
            set
            {
                this.nodeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class folder
    {
        
        private int idField;
        
        private string nameField;
        
        private string pathField;
        
        private int userIdField;
        
        private int nodeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int nodeId
        {
            get
            {
                return this.nodeIdField;
            }
            set
            {
                this.nodeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class response
    {
        
        private int statusCodeField;
        
        private string detailsField;
        
        private string jsonField;
        
        private byte[] fileDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string json
        {
            get
            {
                return this.jsonField;
            }
            set
            {
                this.jsonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] fileData
        {
            get
            {
                return this.fileDataField;
            }
            set
            {
                this.fileDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class registerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.user arg0;
        
        public registerRequest()
        {
        }
        
        public registerRequest(MiReferencia.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class registerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public registerResponse()
        {
        }
        
        public registerResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.user arg0;
        
        public loginRequest()
        {
        }
        
        public loginRequest(MiReferencia.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public loginResponse()
        {
        }
        
        public loginResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolder", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class createFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.folder arg0;
        
        public createFolderRequest()
        {
        }
        
        public createFolderRequest(MiReferencia.folder arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolderResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class createFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public createFolderResponse()
        {
        }
        
        public createFolderResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class uploadFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.file arg0;
        
        public uploadFileRequest()
        {
        }
        
        public uploadFileRequest(MiReferencia.file arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class uploadFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public uploadFileResponse()
        {
        }
        
        public uploadFileResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class downloadFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.file arg0;
        
        public downloadFileRequest()
        {
        }
        
        public downloadFileRequest(MiReferencia.file arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class downloadFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public downloadFileResponse()
        {
        }
        
        public downloadFileResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.file arg0;
        
        public deleteFileRequest()
        {
        }
        
        public deleteFileRequest(MiReferencia.file arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public deleteFileResponse()
        {
        }
        
        public deleteFileResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserFiles", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getUserFilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getUserFilesRequest()
        {
        }
        
        public getUserFilesRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserFilesResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getUserFilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public getUserFilesResponse()
        {
        }
        
        public getUserFilesResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolder", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.folder arg0;
        
        public deleteFolderRequest()
        {
        }
        
        public deleteFolderRequest(MiReferencia.folder arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolderResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class deleteFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public deleteFolderResponse()
        {
        }
        
        public deleteFolderResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class shareFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public shareFileRequest()
        {
        }
        
        public shareFileRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class shareFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public shareFileResponse()
        {
        }
        
        public shareFileResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class stopSharingFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public stopSharingFileRequest()
        {
        }
        
        public stopSharingFileRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class stopSharingFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public stopSharingFileResponse()
        {
        }
        
        public stopSharingFileResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveFile", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class moveFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public moveFileRequest()
        {
        }
        
        public moveFileRequest(int arg0, string arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveFileResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class moveFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public moveFileResponse()
        {
        }
        
        public moveFileResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTree", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class seeStorageTreeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public seeStorageTreeRequest()
        {
        }
        
        public seeStorageTreeRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTreeResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class seeStorageTreeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public seeStorageTreeResponse()
        {
        }
        
        public seeStorageTreeResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifySession", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class verifySessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public verifySessionRequest()
        {
        }
        
        public verifySessionRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifySessionResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class verifySessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiReferencia.response @return;
        
        public verifySessionResponse()
        {
        }
        
        public verifySessionResponse(MiReferencia.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceChannel : MiReferencia.Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MiReferencia.Service>, MiReferencia.Service
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.registerResponse> MiReferencia.Service.registerAsync(MiReferencia.registerRequest request)
        {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.registerResponse> registerAsync(MiReferencia.user arg0)
        {
            MiReferencia.registerRequest inValue = new MiReferencia.registerRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.loginResponse> MiReferencia.Service.loginAsync(MiReferencia.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.loginResponse> loginAsync(MiReferencia.user arg0)
        {
            MiReferencia.loginRequest inValue = new MiReferencia.loginRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.createFolderResponse> MiReferencia.Service.createFolderAsync(MiReferencia.createFolderRequest request)
        {
            return base.Channel.createFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.createFolderResponse> createFolderAsync(MiReferencia.folder arg0)
        {
            MiReferencia.createFolderRequest inValue = new MiReferencia.createFolderRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).createFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.uploadFileResponse> MiReferencia.Service.uploadFileAsync(MiReferencia.uploadFileRequest request)
        {
            return base.Channel.uploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.uploadFileResponse> uploadFileAsync(MiReferencia.file arg0)
        {
            MiReferencia.uploadFileRequest inValue = new MiReferencia.uploadFileRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).uploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.downloadFileResponse> MiReferencia.Service.downloadFileAsync(MiReferencia.downloadFileRequest request)
        {
            return base.Channel.downloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.downloadFileResponse> downloadFileAsync(MiReferencia.file arg0)
        {
            MiReferencia.downloadFileRequest inValue = new MiReferencia.downloadFileRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).downloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.deleteFileResponse> MiReferencia.Service.deleteFileAsync(MiReferencia.deleteFileRequest request)
        {
            return base.Channel.deleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.deleteFileResponse> deleteFileAsync(MiReferencia.file arg0)
        {
            MiReferencia.deleteFileRequest inValue = new MiReferencia.deleteFileRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).deleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.getUserFilesResponse> MiReferencia.Service.getUserFilesAsync(MiReferencia.getUserFilesRequest request)
        {
            return base.Channel.getUserFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.getUserFilesResponse> getUserFilesAsync(int arg0)
        {
            MiReferencia.getUserFilesRequest inValue = new MiReferencia.getUserFilesRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).getUserFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.deleteFolderResponse> MiReferencia.Service.deleteFolderAsync(MiReferencia.deleteFolderRequest request)
        {
            return base.Channel.deleteFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.deleteFolderResponse> deleteFolderAsync(MiReferencia.folder arg0)
        {
            MiReferencia.deleteFolderRequest inValue = new MiReferencia.deleteFolderRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).deleteFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.shareFileResponse> MiReferencia.Service.shareFileAsync(MiReferencia.shareFileRequest request)
        {
            return base.Channel.shareFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.shareFileResponse> shareFileAsync(int arg0, int arg1)
        {
            MiReferencia.shareFileRequest inValue = new MiReferencia.shareFileRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((MiReferencia.Service)(this)).shareFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.stopSharingFileResponse> MiReferencia.Service.stopSharingFileAsync(MiReferencia.stopSharingFileRequest request)
        {
            return base.Channel.stopSharingFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.stopSharingFileResponse> stopSharingFileAsync(int arg0)
        {
            MiReferencia.stopSharingFileRequest inValue = new MiReferencia.stopSharingFileRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).stopSharingFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.moveFileResponse> MiReferencia.Service.moveFileAsync(MiReferencia.moveFileRequest request)
        {
            return base.Channel.moveFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.moveFileResponse> moveFileAsync(int arg0, string arg1, string arg2)
        {
            MiReferencia.moveFileRequest inValue = new MiReferencia.moveFileRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((MiReferencia.Service)(this)).moveFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.seeStorageTreeResponse> MiReferencia.Service.seeStorageTreeAsync(MiReferencia.seeStorageTreeRequest request)
        {
            return base.Channel.seeStorageTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.seeStorageTreeResponse> seeStorageTreeAsync(int arg0)
        {
            MiReferencia.seeStorageTreeRequest inValue = new MiReferencia.seeStorageTreeRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).seeStorageTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiReferencia.verifySessionResponse> MiReferencia.Service.verifySessionAsync(MiReferencia.verifySessionRequest request)
        {
            return base.Channel.verifySessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiReferencia.verifySessionResponse> verifySessionAsync(string arg0)
        {
            MiReferencia.verifySessionRequest inValue = new MiReferencia.verifySessionRequest();
            inValue.arg0 = arg0;
            return ((MiReferencia.Service)(this)).verifySessionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://java.bucaramanga.upb.edu.co/app");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.ServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.ServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicePort,
        }
    }
}
